#!/usr/bin/env bash

last_content=""
now=$(date)

while true; do
    xsel --follow --input --nodetach </dev/null
    content=$(xsel)
    if [[ $last_content != $content ]]; then
        echo "$now;$content" &>> /var/log/clipboard_history.log
    fi
    last_content=$content
done
