#!/bin/bash

if [[ "$(uname)" == "Linux" ]]; then
    echo "you're on an OS that does not support the script"
    exit 1
fi

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

packages=(
    "ffmpeg"
    "gcc"
    "gh"
    "jq"
    "lua"
    "n"
    "ripgrep"
    "neovim"
    "tmux"
    "up"
    "wget"
    "pcre"
    "fzf"
    "zig"
)

casks=(
    "ghostty"
    "cleanshot"
    "firefox"
    "google-drive"
    "lunar"
    "notion-calendar"
    "obs"
    "pictogram"
    "raycast"
    "spotify"
)

for package in "${packages[@]}"; do
  /opt/homebrew/bin/brew install "$package"
done

for package in "${casks[@]}"; do
  /opt/homebrew/bin/brew install --cask "$package"
done
