#!/usr/bin/env bash

paru -S --noconfirm --needed tmux gimp tldr go fzf btop bc stylua node npm xsel
paru -S --noconfirm --needed unzip neovim ttf-dejavu xorg-xrandr xorg-xinput xorg-maim
paru -S --needed --noconfirm zathura zathura-cb zathura-pdf-mupdf
paru -S --noconfirm --needed bluez bluez-utils bluez-deprecated-tools
paru -S --noconfirm --needed slop rofi
paru -S ffmpeg screenkey aalib ascii-image-converter-bin --noconfirm

go install github.com/air-verse/air@latest
