#!/usr/bin/env bash

git clone https://aur.archlinux.org/paru.git $HOME/Programming/paru
cd $HOME/Programming/paru
makepkg -si

hash -r

paru -S --noconfirm --needed tmux gimp fzf bc stylua xsel downgrade bind inetutils nmap
paru -S --noconfirm --needed unzip xorg-xrandr xorg-xinput
paru -S --noconfirm --needed zathura zathura-cb zathura-pdf-mupdf
paru -S --noconfirm --needed bluez bluez-utils bluez-deprecated-tools
paru -S --noconfirm --needed rofi obs-studio
paru -S --noconfirm --needed ffmpeg screenkey fuse3
