#!/usr/bin/env bash

## apt
## https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository

sudo pacman -S docker docker-compose
sudo usermod -aG docker $USER

sudo systemctl start docker
sudo systemctl enable docker
