#!/usr/bin/env bash

sudo pacman -S gtk4 libadwaita blueprint-compiler gettext

wget https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz -O /tmp/zig.tar.xz
tar -xvf /tmp/zig.tar.xz -C $HOME/.local
export PATH="$HOME/.local/zig-linux-x86_64-0.13.0:$PATH"

git clone https://github.com/ghostty-org/ghostty.git $HOME/Programming/ghostty

(
cd $HOME/Programming/ghostty
git checkout v1.0.0
zig build -p $HOME/.local -Doptimize=ReleaseFast
)
