#!/usr/bin/env bash

wget -P $HOME/Downloads https://github.com/be5invis/Iosevka/releases/download/v11.0.0/ttf-iosevka-11.0.0.zip

(
cd $HOME/Downloads
unzip ttf-iosevka-11.0.0.zip
mkdir -p $HOME/.local/share/fonts
mv *.ttf $HOME/.local/share/fonts
)
