#!/usr/bin/env bash

wget https://github.com/be5invis/Iosevka/releases/download/v3.4.1/pkg-iosevka-3.4.1.zip $HOME/Downloads

(
cd $HOME/Downloads
unzip pkg-iosevka-3.4.1.zip
mkdir -p $HOME/.local/share/fonts
cd ttf
ls | grep -E "semibold|medium|regular" | xargs -I {} mv {} $HOME/.local/share/fonts
)
