#!/usr/bin/env bash

sudo pacman -S --noconfirm neovim lua51 luarocks

git clone https://github.com/ThePrimeagen/harpoon.git $HOME/personal/harpoon
cd $HOME/personal/harpoon
git fetch
git checkout harpoon2

git clone https://github.com/nvim-lua/plenary.nvim.git $HOME/personal/plenary.nvim

sudo luarocks install luacheck
