#!/usr/bin/env bash

sudo pacman -S --noconfirm neovim lua51 luarocks

git clone https://github.com/ThePrimeagen/harpoon.git $HOME/Programming/harpoon
cd $HOME/Programming/harpoon
git fetch
git checkout harpoon2

git clone https://github.com/nvim-lua/plenary.nvim.git $HOME/Programming/plenary.nvim

sudo luarocks install luacheck
